# Generated by Django 4.2.1 on 2023-05-27 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_rename_stem_drug_generic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
