# Generated by Django 4.2.1 on 2023-05-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_drug_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='last_modfied',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
