# Generated by Django 4.2.1 on 2023-06-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_drug_last_modfied'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='image',
            field=models.ImageField(default='img/panadol.jpg', upload_to='img/drugs/'),
            preserve_default=False,
        ),
    ]
