# Generated by Django 4.2.1 on 2023-06-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_alter_drug_expiry_date_alter_drug_generic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
