# Generated by Django 4.2.1 on 2023-06-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_doctor_middle_name_patient_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='frontend/static/img/patients/'),
        ),
    ]
